export const IPC_CHANNELS = {
  bootstrap: "workbench/bootstrap",
  setSimpleMode: "workbench/set-simple-mode",
  setAlwaysOnTop: "workbench/set-always-on-top",
  captureTextOrLink: "workbench/capture-text-or-link",
  captureTextOrLinkIntoBox: "workbench/capture-text-or-link-into-box",
  captureImageData: "workbench/capture-image-data",
  captureImageDataIntoBox: "workbench/capture-image-data-into-box",
  captureDroppedPaths: "workbench/capture-dropped-paths",
  captureDroppedPathsIntoBox: "workbench/capture-dropped-paths-into-box",
  createBox: "workbench/create-box",
  updateBox: "workbench/update-box",
  reorderBox: "workbench/reorder-box",
  deleteBox: "workbench/delete-box",
  deleteItem: "workbench/delete-item",
  updateItemTitle: "workbench/update-item-title",
  removeBundleEntry: "workbench/remove-bundle-entry",
  selectBox: "workbench/select-box",
  openPath: "workbench/open-path",
  openExternal: "workbench/open-external",
  copyText: "workbench/copy-text",
  enrichLinkTitle: "workbench/enrich-link-title",
  moveItemToBox: "workbench/move-item-to-box",
  moveItemToIndex: "workbench/move-item-to-index",
  reorderItem: "workbench/reorder-item",
  getBundleEntries: "workbench/get-bundle-entries",
} as const;
